name: Блять

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Pizda:
    runs-on: windows-latest
    steps:
      - name: Чекаут хаха
        uses: actions/checkout@v2
      
      - name: Установкаг овна 
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Компа
        run: msbuild Govno8.sln -p:Configuration=Release

      - name: Загруз очка
        uses: actions/upload-artifact@v2
        with:
          name: Я_ебал_твою_мертвeю_мать
