name: Дилдо
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Дилдо
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Высрать говно
        uses: actions/checkout@v2

      - name: Добавить говно в блендер
        run: git fetch --prune --unshallow

      - name: Добавить мочу в блендер
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.402'

      - name: Добавить блевоту в блендер
        uses: microsoft/setup-msbuild@v1.1

      - name: Подрочить
        run: dotnet tool restore

      - name: Кончить
        run: dotnet fake build

      - name: Выжрать весь этот калл нахуй
        run: msbuild Govno8.sln -p:Configuration=Release

      - name: Выблевать это все нахуй
        uses: actions/upload-artifact@v2
        with:
          name: Я_ебал_твою_мертвeю_мать
